server:
  port: 8999

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90 #服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务（心跳）的调用间隔，单位：秒

spring:
  application:
    name: SUDA-PLATFORM-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: SUDA-PLATFORM-KLINE
          uri: lb://SUDA-PLATFORM-KLINE
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
        - id: SUDA-PLATFORM-WEB
          uri: lb://SUDA-PLATFORM-WEB
          predicates:
            - Path=/platform/**
          filters:
            - StripPrefix=1
        - id: SUDA-ADMIN-WEB
          uri: lb://SUDA-ADMIN-WEB
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1